### PR TITLE
Forms!

### PR DESCRIPTION
**Pull request by renatomefi**
Still WIp

### CODE REVIEW

**Comment by nstapelbroek** [comment]
😭

**Comment by renatomefi** [comment]
@nstapelbroek haha, too late!

**Comment by nstapelbroek** [comment]
@renatomefi Seems like we are missing out 😄 

Maybe we can clean this repo @eXistenZNL ?

**Comment by eXistenZNL** [comment]
Nope we still use this stub on a daily basis while you guys have since moved on with your lives :cry:

**Pull request closed without merging**
